name = "lumiloki-contact-form"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
TO_EMAIL = "support@lumiloki.com"
ALLOWED_ORIGINS = "https://www.lumiloki.com,https://lumiloki.com,https://libercube.github.io,http://localhost:5173"

[dev]
port = 8787
